spring:
  application:
    name: library-management-system

  datasource:
    url: "jdbc:mysql://localhost:3306/lms-database"
    username: "lms-user"
    password: "lmsPassword"
    hikari:
      schema: lms-database

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

server:
  port: 8080

loggin:
  level:
    root: error
    org.springframework: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %level [%thread] [%file:%line] %msg%n"

